"""new seq ids v2

Revision ID: 112a29ffbae9
Revises: 8e3cc97f084d
Create Date: 2019-02-11 17:04:44.338616

"""
from alembic import op
import sqlalchemy as sa
import fix_seq


# revision identifiers, used by Alembic.
revision = '112a29ffbae9'
down_revision = '8e3cc97f084d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    connection = op.get_bind()

    affected_tables = [
        'enevo_filllevel',
        'enevo_filllevel_raw',
        'kilogram_weigh_raw',
        'kilogram_weigh_measurement',
        'sidcon_container_status_raw',
        'sidcon_container_states',
    ]

    for table in affected_tables:
        fix_seq.fix_table(connection, table)


def downgrade():
    pass
