"""create short_id site column

Revision ID: 79cb4b3c0ff9
Revises: f24f02bdf8a4
Create Date: 2019-01-28 15:26:33.834651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cb4b3c0ff9'
down_revision = 'f24f02bdf8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidcon_container_states', sa.Column('short_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sidcon_container_states_short_id'), 'sidcon_container_states', ['short_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sidcon_container_states_short_id'), table_name='sidcon_container_states')
    op.drop_column('sidcon_container_states', 'short_id')
    # ### end Alembic commands ###
