"""new seq ids

Revision ID: 8e3cc97f084d
Revises: ca54373f9692
Create Date: 2019-02-06 16:03:57.491467

"""
import logging
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import fix_seq
# revision identifiers, used by Alembic.
revision = '8e3cc97f084d'
down_revision = 'ca54373f9692'
branch_labels = None
depends_on = None

LOG = logging.getLogger(__name__)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    connection = op.get_bind()

    affected_tables = [
        # 'enevo_filllevel',
        # 'enevo_filllevel_raw',

        'sidcon_container_status_raw',
        'sidcon_container_states',
    ]

    for table in affected_tables:
        fix_seq.fix_table(connection, table)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
