# Generated by Django 2.1.2 on 2018-12-10 13:27

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buurten',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=14)),
                ('vollcode', models.CharField(max_length=4)),
                ('naam', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'buurt_simple',
                'managed': settings.TESTING
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(db_index=True, max_length=35)),
                ('serial_number', models.CharField(db_index=True, max_length=45)),
                ('owner', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('active', models.IntegerField(null=True)),
                ('waste_type', models.IntegerField(db_index=True, null=True)),
                ('waste_name', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(null=True)),
                ('placing_date', models.DateTimeField(null=True)),
                ('operational_date', models.DateTimeField(null=True)),
                ('warranty_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('short_id', models.IntegerField(null=True, unique=True)),
                ('buurt_code', models.CharField(max_length=20)),
                ('stadsdeel', models.CharField(max_length=1)),
                ('stadsdeel_naam', models.CharField(max_length=20)),
                ('straatnaam', models.CharField(max_length=40)),
                ('huisnummer', models.IntegerField(null=True)),
                ('distance', models.IntegerField(null=True)),
                ('bgt_based', models.NullBooleanField()),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geometrie', django.contrib.gis.db.models.fields.PolygonField(srid=28992)),
                ('extra_attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('active', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteFractie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fractie', models.CharField(db_index=True, max_length=20)),
                ('containers', models.IntegerField(default=0, null=True)),
                ('volume_m3', models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fracties', to='afvalcontainers.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(db_index=True, max_length=35)),
                ('serial_number', models.CharField(db_index=True, max_length=45)),
                ('active', models.IntegerField(null=True)),
                ('owner', django.contrib.postgres.fields.jsonb.JSONField()),
                ('containers_bron', django.contrib.postgres.fields.jsonb.JSONField()),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geometrie_rd', django.contrib.gis.db.models.fields.PointField(null=True, srid=28992)),
                ('stadsdeel', models.CharField(max_length=1, null=True)),
                ('buurt_code', models.CharField(max_length=4, null=True)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('placing_date', models.DateTimeField(null=True)),
                ('warranty_date', models.DateTimeField(null=True)),
                ('operational_date', models.DateTimeField(null=True)),
                ('extra_attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='afvalcontainers.Site')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='afvalcontainers.ContainerType'),
        ),
        migrations.AddField(
            model_name='container',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='afvalcontainers.Well'),
        ),
    ]
