# Generated by Django 2.0.4 on 2018-04-23 12:57

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(db_index=True, max_length=35)),
                ('serial_number', models.CharField(db_index=True, max_length=45)),
                ('owner', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('active', models.NullBooleanField()),
                ('waste_type', models.IntegerField(null=True)),
                ('waste_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(null=True)),
                ('placing_date', models.DateTimeField(null=True)),
                ('operational_date', models.DateTimeField(null=True)),
                ('warranty_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(db_index=True, max_length=35)),
                ('serial_number', models.CharField(db_index=True, max_length=45)),
                ('active', models.NullBooleanField()),
                ('owner', django.contrib.postgres.fields.jsonb.JSONField()),
                ('containers_bron', django.contrib.postgres.fields.jsonb.JSONField()),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('stadsdeel', models.CharField(max_length=1, null=True)),
                ('buurt_code', models.CharField(max_length=4, null=True)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('placing_date', models.DateTimeField(null=True)),
                ('warranty_date', models.DateTimeField(null=True)),
                ('operational_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='afvalcontainers.ContainerType'),
        ),
        migrations.AddField(
            model_name='container',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='afvalcontainers.Well'),
        ),
    ]
