# Generated by Django 2.0.1 on 2018-04-25 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buurten',
            fields=[
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=14)),
                ('vollcode', models.CharField(max_length=4)),
                ('naam', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'buurt_simple',
            },
        ),
    ]
