# Generated by Django 2.0.1 on 2018-07-19 08:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0003_well_extra_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='geometrie_rd',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=28992),
        ),
    ]
