# Generated by Django 2.0.1 on 2018-07-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0005_auto_20180724_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='buurtcode',
            new_name='buurt_code',
        ),
    ]
