# Generated by Django 2.1.1 on 2018-09-18 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0008_containertype_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='short_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='extra_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
