# Generated by Django 2.1.1 on 2018-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0009_auto_20180918_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
