# Generated by Django 2.1.1 on 2018-10-03 07:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0010_site_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='extra_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
