# Generated by Django 2.1.2 on 2018-10-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0011_auto_20181003_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFractie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fractie', models.CharField(db_index=True, max_length=20)),
                ('containers', models.IntegerField(default=0, null=True)),
                ('volume_m3', models.IntegerField(default=0, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fracties', to='afvalcontainers.Site')),
            ],
        ),
    ]
