# Generated by Django 2.1.2 on 2018-11-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0012_sitefractie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='active',
            field=models.IntegerField(null=True),
        ),
    ]
