# Generated by Django 2.1.2 on 2018-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afvalcontainers', '0013_auto_20181112_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='active',
            field=models.IntegerField(null=True),
        ),
    ]
