version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: afvalcontainers
      POSTGRES_USER: afvalcontainers
      POSTGRES_PASSWORD: insecure
    volumes:
      - ~/.ssh/datapunt.key:/root/.ssh/datapunt.key
      - ./backups:/tmp/backups

  scrape_api:
    build: ./scrape_api
    links:
      - database
    environment:
      BAMMENS_API_USERNAME:
      BAMMENS_API_PASSWORD:
      KILOGRAM_API_PASSWORD:

  api:
    build: ./api
    ports:
      - "8001:8000"
    links:
      - database
    environment:
      - DATABASE_NAME=afvalcontainers
      - DATABASE_PASSWORD=insecure
      - DATABASE_KILOGRAM_PASSWORD=insecure
      - DATABASE_KILOGRAM_NAME=afvalcontainers
      - UWSGI_HTTP=":8000"
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/afval/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=afvalcontainers.wsgi:application
