version: '2.0'
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: afvalcontainers
      POSTGRES_USER: afvalcontainers
      POSTGRES_PASSWORD: insecure
  cmsdownloader:
    build: ./cmsdownloader
    links:
      - database
    environment:
      CKAN_API_KEY:
      BAMMENS_API_USERNAME:
      BAMMENS_API_PASSWORD:

