FROM amsterdam/python


RUN adduser --system datapunt
RUN rm -rf /data
RUN mkdir /data
RUN chown datapunt /data

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

USER datapunt

CMD /app/docker-run.sh