FROM amsterdam/python

RUN rm -rf /data
RUN mkdir /data

ADD /requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY . /app/

ADD /run_cmsdownloader.sh /app/run_cmsdownloader.sh
ADD /run_load_json2pg.sh /app/run_load_json2pg.sh
ADD /run_load_json2pg.sh /app/run_json2geojson.sh