# Generated by Django 2.1.2 on 2018-11-22 15:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('fill_level', models.IntegerField()),
                ('site', models.IntegerField()),
                ('site_name', models.CharField(max_length=100)),
                ('site_content_type', models.IntegerField()),
                ('content_type', models.IntegerField()),
                ('content_type_name', models.CharField(max_length=100)),
                ('confidence', models.IntegerField()),
                ('frozen', models.NullBooleanField()),
            ],
            options={
                'db_table': 'enevo_filllevel',
                'managed': settings.TESTING,
            },

        ),
        migrations.CreateModel(
            name='EnevoAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('type_name', models.CharField(max_length=100)),
                ('reported', models.DateTimeField()),
                ('last_observed', models.DateTimeField()),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('content_type_name', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnevoContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('geometrie_rd', django.contrib.gis.db.models.fields.PointField(null=True, srid=28992)),
                ('geo_accuracy', models.IntegerField(null=True)),
                ('customer_key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnevoContainerSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('container', models.IntegerField(blank=True, null=True)),
                ('site_fk', models.IntegerField(null=True)),
                ('site_content_type_fk', models.IntegerField(null=True)),
                ('fill_level', models.IntegerField(blank=True, null=True)),
                ('date_when_full', models.DateTimeField(blank=True, null=True)),
                ('last_service_event', models.DateTimeField(blank=True, null=True)),
                ('photo', models.NullBooleanField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnevoContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('sensor_height', models.FloatField()),
                ('full_height', models.FloatField()),
                ('shape', models.CharField(max_length=100)),
                ('has_bag', models.NullBooleanField()),
                ('servicing_amount', models.CharField(max_length=100)),
                ('servicing_method', models.CharField(max_length=100)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnevoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('weight_to_volume_ratio', models.FloatField()),
                ('last_modified', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnevoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geometrie_rd', django.contrib.gis.db.models.fields.PointField(null=True, srid=28992)),
                ('photo', models.NullBooleanField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnevoSiteContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('fill_level', models.IntegerField(blank=True, null=True)),
                ('date_when_full', models.DateTimeField(blank=True, null=True)),
                ('build_up_rate', models.FloatField(blank=True, null=True)),
                ('fill_up_time', models.IntegerField(blank=True, null=True)),
                ('last_service_event', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_content_types', to='enevo.EnevoContentType')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_content_types', to='enevo.EnevoSite')),
            ],
        ),
        migrations.AddField(
            model_name='enevocontainerslot',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='container_slots', to='enevo.EnevoContentType'),
        ),
        migrations.AddField(
            model_name='enevocontainerslot',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='container_slots', to='enevo.EnevoSite'),
        ),
        migrations.AddField(
            model_name='enevocontainerslot',
            name='site_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='container_slots', to='enevo.EnevoSiteContentType'),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='container_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='enevo.EnevoContainerSlot'),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='container_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='enevo.EnevoContainerType'),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='enevo.EnevoSite'),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='site_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='containers', to='enevo.EnevoSiteContentType'),
        ),
        migrations.AddField(
            model_name='enevoalert',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alerts', to='enevo.EnevoContentType'),
        ),
        migrations.AddField(
            model_name='enevoalert',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alerts', to='enevo.EnevoSite'),
        ),
    ]
