# Generated by Django 2.1.2 on 2019-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enevo', '0002_enevocontainer_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnevoFillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('fill_level', models.IntegerField()),
                ('e_site', models.IntegerField()),
                ('e_site_name', models.CharField(max_length=100)),
                ('e_site_content_type', models.IntegerField()),
                ('content_type', models.IntegerField()),
                ('content_type_name', models.CharField(max_length=100)),
                ('confidence', models.IntegerField()),
                ('frozen', models.NullBooleanField()),
            ],
            options={
                'db_table': 'enevo_filllevel',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='enevocontainer',
            name='container_slot',
        ),
        migrations.RemoveField(
            model_name='enevocontainer',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='enevocontainer',
            name='site',
        ),
        migrations.RemoveField(
            model_name='enevocontainer',
            name='site_content_type',
        ),
        migrations.RemoveField(
            model_name='enevocontainerslot',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='enevocontainerslot',
            name='site',
        ),
        migrations.RemoveField(
            model_name='enevocontainerslot',
            name='site_content_type',
        ),
        migrations.RemoveField(
            model_name='enevositecontenttype',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='enevositecontenttype',
            name='site',
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='container_slot_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='container_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='site_content_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevocontainer',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevocontainerslot',
            name='content_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevocontainerslot',
            name='site_content_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevocontainerslot',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevositecontenttype',
            name='content_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enevositecontenttype',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
    ]
