# Generated by Django 2.1.2 on 2018-12-17 13:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidconFillLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('placement_date', models.DateTimeField(blank=True, null=True)),
                ('communication_date_time', models.DateTimeField(blank=True, null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('valid', models.NullBooleanField()),
                ('_id', models.IntegerField()),
                ('filling', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('limit_full', models.IntegerField(blank=True, null=True)),
                ('limit_near_full', models.IntegerField(blank=True, null=True)),
                ('nr_press_strokes', models.IntegerField(blank=True, null=True)),
                ('drum_action_count', models.IntegerField(blank=True, null=True)),
                ('network_strenght', models.IntegerField(blank=True, null=True)),
                ('status_incidents', models.IntegerField(blank=True, null=True)),
                ('max_nr_press_strokes', models.IntegerField(blank=True, null=True)),
                ('drum_position_status', models.IntegerField(blank=True, null=True)),
                ('lock_position_status', models.IntegerField(blank=True, null=True)),
                ('total_nr_press_strokes', models.IntegerField(blank=True, null=True)),
                ('total_nr_empty_detected', models.IntegerField(blank=True, null=True)),
                ('nr_press_strokes_to_go', models.IntegerField(blank=True, null=True)),
                ('max_dump_count_on_dump_location', models.IntegerField(blank=True, null=True)),
                ('successfull_transaction_since_reset', models.IntegerField(blank=True, null=True)),
                ('unsuccessfull_transaction_since_reset', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status_device', models.CharField(blank=True, max_length=50, null=True)),
                ('container_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status_chip_cards', models.CharField(blank=True, max_length=50, null=True)),
                ('status_container', models.CharField(blank=True, max_length=50, null=True)),
                ('status_trigger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status_configuration', models.CharField(blank=True, max_length=50, null=True)),
                ('fraction', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sidcon_container_states',
                'managed': settings.TESTING,
            },
        ),
    ]
