# Generated by Django 2.1.1 on 2018-10-10 12:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KilogramWeighMeasurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seq_id', models.IntegerField(blank=True, null=True)),
                ('system_id', models.IntegerField(blank=True, null=True)),
                ('weigh_at', models.DateTimeField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('container_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fractie', models.CharField(blank=True, max_length=200, null=True)),
                ('first_weight', models.IntegerField(blank=True, null=True)),
                ('second_weight', models.IntegerField(blank=True, null=True)),
                ('net_weight', models.IntegerField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'kilogram_weigh_measurement',
                'managed': False,
            },
        ),
    ]
