# Generated by Django 2.1.2 on 2018-10-23 15:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models

from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KilogramWeighMeasurement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seq_id', models.IntegerField(blank=True, null=True)),
                ('system_id', models.IntegerField(blank=True, null=True)),
                ('weigh_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('container_ids', models.CharField(blank=True, max_length=200, null=True)),
                ('fractie', models.CharField(blank=True, max_length=200, null=True)),
                ('stadsdeel', models.CharField(blank=True, max_length=1, null=True)),
                ('buurt_code', models.CharField(blank=True, max_length=4, null=True)),
                ('first_weight', models.IntegerField(blank=True, null=True)),
                ('second_weight', models.IntegerField(blank=True, null=True)),
                ('net_weight', models.IntegerField(blank=True, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('valid', models.NullBooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kilogram_weigh_measurement',
                'managed': settings.TESTING,
            },
        ),
    ]
