# Generated by Django 2.1.2 on 2018-10-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0002_buurtfractiestatmonth_buurtfractiestatweek_sitefractiestatmonth_sitefractiestatweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buurtfractiestatmonth',
            old_name='wegingen',
            new_name='measurements',
        ),
        migrations.RenameField(
            model_name='buurtfractiestatweek',
            old_name='wegingen',
            new_name='measurements',
        ),
        migrations.RenameField(
            model_name='sitefractiestatmonth',
            old_name='wegingen',
            new_name='measurements',
        ),
        migrations.RenameField(
            model_name='sitefractiestatweek',
            old_name='wegingen',
            new_name='measurements',
        ),
    ]
