# Generated by Django 2.1.2 on 2018-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0003_auto_20181030_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitefractiestatmonth',
            name='containers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitefractiestatmonth',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitefractiestatweek',
            name='containers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitefractiestatweek',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
