version: '3.0'
services:
  importer:
    image: docker-registry.data.amsterdam.nl/datapunt/afvalcontainers_importer:${ENVIRONMENT}
    # build: ../../
    environment:
      ENVIRONMENT:
      KILOGRAM_API_PASSWORD:
      SIDCON_PASSWORD:
      ENEVO_API_PASSWORD:
      ENEVO_API_USERNAME:
      DATABASE_NAME: kilogram
      DATABASE_USER: kilogram
      DATABASE_KILOGRAM_PASSWORD:
      DATABASE_KILOGRAM_NAME: kilogram
      DATABASE_KILOGRAM_HOST:
      DATABASE_KILOGRAM_USER: kilogram
      DATABASE_KILOGRAM_PORT: 5432
      TENANT_NAME: BGE000081_afvalbakken
      TENANT_ID: 010f69210d4f4d5c96da979f723350a9
      OBJECTSTORE_USER: afvalbakken
      OBJECTSTORE_PASSWORD:
      OBJECTSTORE_LOCAL:
      PYTHONPATH: /app/
