version: '3.0'
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: afvalcontainers
      POSTGRES_DB: afvalcontainers
    volumes:
      - ./backups:/tmp/backups

  api:
    image: build.datapunt.amsterdam.nl:5000/afvalcontainers:${ENVIRONMENT}
    links:
      - database
    environment:
      DATABASE_NAME: afvalcontainers
      DATABASE_USER: afvalcontainers

  importer:
    image: build.datapunt.amsterdam.nl:5000/afvalcontainers_importer:${ENVIRONMENT}
    links:
      - database
    environment:
      DATABASE_USER: afvalcontainers
      DATABASE_PASSWORD: insecure
      BAMMENS_API_USERNAME:
      BAMMENS_API_PASSWORD:
      TENANT_NAME: BGE000081_afvalbakken
      TENANT_ID: 97d77d9423fe46df8675937493b8521e
      OBJECTSTORE_USER: afvalbakken
      OBJECTSTORE_PASSWORD:

    volumes:
      - afvalcontainers_import_cache:/data
    command: >
      bash -c "/deploy/import/import.sh"

volumes:
  afvalcontainers_import_cache:
