version: '3.0'
services:
  importer:
    image: build.datapunt.amsterdam.nl:5000/afvalcontainers_importer:${ENVIRONMENT}
    # build: ../../
    environment:
      ENVIRONMENT:
      DATABASE_NAME: kilogram
      DATABASE_USER: kilogram
      DATABASE_KILOGRAM_PASSWORD:
      DATABASE_KILOGRAM_NAME: kilogram
      DATABASE_KILOGRAM_HOST:
      DATABASE_KILOGRAM_PORT: 5432
      TENANT_NAME: BGE000081_afvalbakken
      TENANT_ID: 010f69210d4f4d5c96da979f723350a9
      OBJECTSTORE_USER: afvalbakken
      OBJECTSTORE_PASSWORD:
      PYTHONPATH: /app/
